name:             blog
version:          0.1.2.0
synopsis:         Personal blog web system
category:         Web
author:           Justin Le
maintainer:       justin@jle.im
license:          BSD3

ghc-options:
- -Wall
- -fwarn-redundant-constraints
- -Werror=incomplete-patterns
- -Wcompat

dependencies:
- base >=4 && <5
- aeson
- containers
- data-default
- filepath
- hakyll >=4.8
- pandoc
- text
- time
- transformers
- yaml
- bytestring
- dhall >= 1.29
- lens

library:
  source-dirs: src
  dependencies:
  - binary
  - binary-instances
  - binary-orphans
  - blaze-html
  - blaze-markup
  - feed
  - hakyll-dhall >= 0.2.3
  - hakyll-sass
  - hjsmin
  - hsass
  - inliterate
  - pandoc-types
  - parsec
  - xml-conduit
  - xml-types

executables:
  blog-migrate-entries:
    main: app/migrate-entries.hs
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - cases
    - directory
    - optparse-applicative
    - scientific
    - vector
  blog-build:
    main: app/site.hs
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - blog
    - prettyprinter
    - prettyprinter-ansi-terminal
